import { createElement } from '@lwc/engine-dom';
import TanqueUploader from 'c/tanqueUploader';

describe('c-tanque-uploader', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-tanque-uploader', {
            is: TanqueUploader
        });

        // Act
        document.body.appendChild(element);

        
        expect(1).toBe(1);
    });
});